### ISSUE TITLE
more detail 

### ISSUE THREAD

**Issue by 943fansi** [wxwmd/time-series-dl-attack#1]
Hi @wxwmd ,  I am interested with this work. But I don't know where to start running the code. Could you please help me?

Looking forward to your reply.

**Comment by wxwmd** [comment]
收到

**Comment by wxwmd** [comment]
hi, @943fansi , the code of this repo is mainly from https://github.com/Harry24k/adversarial-attacks-pytorch, you can found various attacks there.
Good luck!



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wxwmd/time-series-dl-attack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月16日(星期四) 晚上6:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;[wxwmd/time-series-dl-attack] more detail  (Issue #1)





 
Hi @wxwmd ,  I am interested with this work. But I don't know where to start running the code. Could you please help me?
 
Looking forward to your reply.

**Comment by 943fansi** [comment]
@wxwmd Thanks for your help. That's great to know! 

Cheers!
